### ISSUE TITLE
where are the proxy questions?

### ISSUE THREAD

**Issue by 3244we** [Namco0816/ProxyQA#1]
Has your complete dataset been released, including proxy questions, and preferably with a standard format to evaluate prompt.

**Comment by Namco0816** [comment]
unlike previous datasets compiled from online sources (Nguyen et al., 2016; Fan et al., 2019a) that potentially leading to data contamination (Sainz et al., 2023), all the proxy-questions and answers are invisible to public, thereby preventing data leakage. Each meta-question accompany various proxy-questions with annotated answer, which are invisible to the LLMs to be tested. To proxy the objective evaluation of the generated contents to subjective metrics, we adopt an evaluator that take the generated contents as contextual background, and answer the proxy-questions. We assume that only if the contextual background is informative and comprehensive, can the proxy-questions be well-addressed by the evaluator. 

If you want to submit the result and check the result, please check https://proxy-qa.com/

**Comment by 3244we** [comment]
> unlike previous datasets compiled from online sources (Nguyen et al., 2016; Fan et al., 2019a) that potentially leading to data contamination (Sainz et al., 2023), all the proxy-questions and answers are invisible to public, thereby preventing data leakage. Each meta-question accompany various proxy-questions with annotated answer, which are invisible to the LLMs to be tested. To proxy the objective evaluation of the generated contents to subjective metrics, we adopt an evaluator that take the generated contents as contextual background, and answer the proxy-questions. We assume that only if the contextual background is informative and comprehensive, can the proxy-questions be well-addressed by the evaluator.
> 
> If you want to submit the result and check the result, please check https://proxy-qa.com/

Thanks for your reply, but only releasing meta questions may limit the use and impact of the dataset.
